---

- name: Config hosts
  hosts: all
  become: true
  tasks:
    - name: Configure inetRouter
      when: (inventory_hostname == "inetRouter")
      block:
        - name: Install iptables
          ansible.builtin.yum:
            name:
              - iptables
              - iptables-services
            state: present
            update_cache: true

        - name: Copy iptables config
          ansible.builtin.template:
            src: iptables
            dest: /etc/sysconfig/iptables
            owner: root
            group: root
            mode: 0600

        - name: Start and enable iptables service
          ansible.builtin.systemd:
            name: iptables
            state: restarted
            enabled: true

        - name: Set up route on inetRouter
          ansible.builtin.template:
            src: inetRouter_route_eth1.j2
            dest: /etc/sysconfig/network-scripts/route-eth1
            owner: root
            group: root
            mode: 0644

        - name: Restart network service
          ansible.builtin.systemd:
            name: network
            state: restarted

    - name: Set up forward packages across routers
      ansible.posix.sysctl:
        name: net.ipv4.conf.all.forwarding
        value: '1'
        state: present
      when: "'routers' in group_names"

    - name: Configure centralRouter
      when: (inventory_hostname == "centralRouter")
      block:
        - name: Disable default route
          ansible.builtin.lineinfile:
            dest: /etc/sysconfig/network-scripts/ifcfg-eth0
            line: DEFROUTE=no

        - name: Add default gateway for centralRouter
          ansible.builtin.lineinfile:
            dest: /etc/sysconfig/network-scripts/ifcfg-eth1
            line: GATEWAY=192.168.255.1

        - name: Set up route on eth5
          ansible.builtin.template:
            src: centralRouter_route_eth5.j2
            dest: /etc/sysconfig/network-scripts/route-eth5
            owner: root
            group: root
            mode: 0644

        - name: Set up route on eth6
          ansible.builtin.template:
            src: centralRouter_route_eth6.j2
            dest: /etc/sysconfig/network-scripts/route-eth6
            owner: root
            group: root
            mode: 0644

        - name: Restart network service
          ansible.builtin.systemd:
            name: network
            state: restarted

    - name: Configure centralServer
      when: (inventory_hostname == "centralServer")
      block:
        - name: Disable default route
          ansible.builtin.lineinfile:
            dest: /etc/sysconfig/network-scripts/ifcfg-eth0
            line: DEFROUTE=no

        - name: Add default gateway for centralServer
          ansible.builtin.lineinfile:
            dest: /etc/sysconfig/network-scripts/ifcfg-eth1
            line: GATEWAY=192.168.0.1

        - name: Restart network service
          ansible.builtin.systemd:
            name: network
            state: restarted

    - name: Configure office1Router
      when: (inventory_hostname == "office1Router")
      block:
        - name: Set up route on office1Router
          ansible.builtin.template:
            src: office1Router_route.j2
            dest: /etc/netplan/50-vagrant.yaml
            owner: root
            group: root
            mode: 0644

        - name: Apply netplan on office1Router
          ansible.builtin.command: netplan apply

    - name: Configure office1Server
      when: (inventory_hostname == "office1Server")
      block:
        - name: Set up route on office1Server
          ansible.builtin.template:
            src: office1Server_route.j2
            dest: /etc/netplan/50-vagrant.yaml
            owner: root
            group: root
            mode: 0644

        - name: Apply netplan on office1Server
          ansible.builtin.command: netplan apply

    - name: Configure office2Router
      when: (inventory_hostname == "office2Router")
      block:
        - name: Set up route on office2Router
          ansible.builtin.template:
            src: office2Router_route.j2
            dest: /etc/network/interfaces
            owner: root
            group: root
            mode: 0644

        - name: Restart network service
          ansible.builtin.systemd:
            name: networking
            state: restarted

    - name: Configure office2Server
      when: (inventory_hostname == "office2Server")
      block:
        - name: Set up route on office2Server
          ansible.builtin.template:
            src: office2Server_route.j2
            dest: /etc/network/interfaces
            owner: root
            group: root
            mode: 0644

        - name: Restart network service
          ansible.builtin.systemd:
            name: networking
            state: restarted

    - name: Reboot Servers
      ansible.builtin.reboot:
    - name: Install traceroute on Centos
      ansible.builtin.yum:
        name: traceroute
        state: present
        update_cache: true
      when: (ansible_distribution == 'CentOS')

    - name: Install traceroute on Debian
      ansible.builtin.apt:
        name: traceroute
        state: present
        update_cache: true
      when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
